name: batufo
description: UFO multi-player game using Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: 0.24.0
  logging: ^0.11.4
  socket_io_client: ^0.9.10

  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg/
    - assets/images/sprites/
    - assets/images/static/
